import "@/styles/globals.css";

import { Layout } from "@/components/layout"

export const metadata = {
    // title: 'Site.blog',
    description: 'Generated by Next.js'
}

export default function RootLayout({
    children
} : {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Layout>
                    {children}
                </Layout>
            </body>
        </html>
    )
}